language: python

python:
  - "2.7.17"
  - "3.5.9"
  - "3.6.10"
  - "3.7.7"
  - "3.8.2"

env:
  - CPPFLAGS=--coverage

before_script:
  - pip install cpp-coveralls

script:
  - python setup.py test

after_success:
  - coveralls --build-root .
  - bash <(curl -s https://codecov.io/bash)
